{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Программирование на языке Python. Уровень 1.\u000b",
    "Основы языка Python\n",
    "\n",
    "## Модуль 7b. Обработка исключений\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Обработка исключений\n",
    "\n",
    "Исключение - некое особое событие, которое возникает при выполнении программы, и если оно не \"поймано\" - программа прекращает свою работу.\n",
    "\n",
    "Любая ошибка, возникшая во время выполнения программы является исключением, появление котрого можно обработать программно.\n",
    "\n",
    "Исключения можно не только \"ловить\" но и \"выбрасывать\" самому командой ```raise```.\n",
    "\n",
    "Исключения - удобный способ обработки ошибок и нестандартных ситуаций.\n",
    "\n",
    "Как выглядит обработка исключений:\n",
    " - попытаться (try) выполнить некоторое количество команд в блоке ``` try```\n",
    " - если в какой-либо из них произойдет сбой, то есть будет \"выброшено\" исключение, выполнение кода пректатится\n",
    " - произойдет переход в блок ```except```, в зависимости от класса исключения\n",
    " - выполнение самой программы продолжится после выполнения блока ```finally```\n",
    "\n",
    "```python\n",
    "try:\n",
    "    блок, в котором\n",
    "    мы ожидаем\n",
    "    выброса исключения\n",
    "except IndexError :\n",
    "    этот блок выполняется,\n",
    "    если было выброшено\n",
    "    исключение типа IndexError\n",
    "except ZeroDivisionError :\n",
    "    этот блок выполняется,\n",
    "    если было выброшено\n",
    "    исключение типа ZeroDivisionError\n",
    "except Exception :\n",
    "    этот блок выполняется,\n",
    "    если было выброшено\n",
    "    исключение ЛЮБОГО ТИПА, не \"пойманное\" ранее\n",
    "else:\n",
    "    этот блок выполняется,\n",
    "    если никакого исключения\n",
    "    выброшено не было\n",
    "finally:\n",
    "    этот блок выполняется\n",
    "    независимо от того,\n",
    "    выброшено исключение\n",
    "    или нет\n",
    "\n",
    "```\n",
    "\n",
    "Распространенные типы исключений:\n",
    "\n",
    " - Exception - тип, общий для всех исключений\n",
    " - ZeroDivisionError - попытка деления на ноль\n",
    " - ValueError - попытка выполнить операцию, которую нельзя выполнить с этим значением, например, извлечь квадратный корень из отрицательного числа\n",
    " - IndexError - обращение к несуществующему элементу списка\n",
    " - KeyError - обращение к несуществующему элементу словаря\n",
    " - ImportError - ошибка импорта модуля\n",
    " - AttributeError - обращение к несуществующему атрибуту объекта\n",
    " - KeyboardInterrupt - пользователь нажал Ctrl-C на клавиатуре\n",
    " - UnicodeError - ошибка перекодирования текста\n",
    " - TypeError - недопустимый тип значения\n",
    " - IOError - ошибка ввода-вывода"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def NOD( A, B ):\n",
    "    \"\"\"\n",
    "    Вычисление наибольшего общего делителя чисел A и B\n",
    "    \"\"\"\n",
    "    if A < B :\n",
    "        ( A, B ) = ( B, A )\n",
    "    ( A, B ) = ( B, A % B )\n",
    "    while B > 0 :\n",
    "        ( A, B ) = ( B, A % B )\n",
    "    return A\n",
    "\n",
    "A = int(input(\"Введите число A: \"))\n",
    "B = int(input(\"Введите число В: \"))\n",
    "print( NOD(A,B) )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# теперь с исключениями\n",
    "try :\n",
    "    A = int(input(\"Введите число A: \"))\n",
    "    B = int(input(\"Введите число В: \"))\n",
    "    print( NOD(A,B) )\n",
    "    \n",
    "except ValueError :\n",
    "    print(f\"Число введено некорректно\")\n",
    "except ZeroDivisionError :\n",
    "    print(\"Попытка деления на нуль\")\n",
    "else:\n",
    "    print(\"Программа выполнена успешно\")\n",
    "finally :\n",
    "    print(\"Расчет окончен\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Утверждение (assertion)\n",
    "\n",
    "Инструкция ```assert``` утверждает некоторое выражение, которое в результате возвращает ```True``` или ```False```. Если выражение возвращает ```False```, Python выбрасывает исключение ```AssertionError```. Выражение ```assert``` удобно использовать для контроля качества входных данных в вашей программе, не прибегая к сложным ветвлениям."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Введите число: 123\n"
     ]
    },
    {
     "ename": "AssertionError",
     "evalue": "должно быть целое число",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAssertionError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-2-62c7a18a3174>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mnum_\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 7\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnum_2\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnum\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m<ipython-input-2-62c7a18a3174>\u001b[0m in \u001b[0;36mnum_2\u001b[0;34m(num_)\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mnum_2\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnum_\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m     \u001b[0;32massert\u001b[0m \u001b[0mtype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnum_\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mint\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'должно быть целое число'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      5\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mnum_\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mAssertionError\u001b[0m: должно быть целое число"
     ]
    }
   ],
   "source": [
    "num = input(\"Введите число: \")\n",
    "\n",
    "def num_2(num_):\n",
    "    assert type(num_) == int, 'должно быть целое число'\n",
    "    return num_*2\n",
    "\n",
    "print(num_2(num))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Исключение - это объект, созданный на базе класса ```Exception```. В блоке обработки исключений его можно передать в переменную (ее, как правило, именуют ```e```). Тогда информацию об ошибке можно найти в кортеже ```e.args```."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Введите число: 123\n",
      "('должно быть целое число',)\n"
     ]
    }
   ],
   "source": [
    "num = input(\"Введите число: \")\n",
    "\n",
    "def num_2(num_):\n",
    "    assert type(num_) == int, 'должно быть целое число'\n",
    "    return num_*2\n",
    "\n",
    "try:\n",
    "    print(num_2(num))\n",
    "except AssertionError as e:\n",
    "    print(e.args)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Создание исключений\n",
    "\n",
    "Если условие, которое требует обработки исключительных ситуаций, выходит за рамки синтаксиса оператора ```assert```, мы можем сгенерировать исключение сами. Это делается при помощи оператора ```raise```, ему в качестве параметра передается объект класса ```Exception``` или производного от него. В него можно поместить всю необходимую отладочную информацию (подобно письму в бутылке при кораблекрушении)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# пробуем сами выбросить исключение\n",
    "\n",
    "def check_is_5( num ) :\n",
    "    num_int = int(num)\n",
    "    if num_int != 5:\n",
    "        raise Exception(\"Это не 5. Дайте другое число.\")\n",
    "\n",
    "num = input(\"Введите число: \")\n",
    "\n",
    "try:\n",
    "    check_is_5( num )\n",
    "    print(\"5 - это хорошо.\")\n",
    "except ValueError :\n",
    "    print(f\"Число введено некорректно: \\\"{num}\\\"\")\n",
    "except Exception as e:\n",
    "    print(e.args[0])\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### Практика\n",
    "\n",
    "1. Напишите функцию, которая вычисляет среднее геометрическое двух чисел (квадратный корень из их произведения). В случае невозможности вычисления такого среднего (когда произведение чисел отрицательно) выбросите исключение. Обработайте исключение и выведите ответ в дружелюбной форме."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ваш код здесь\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
